# Generated by Django 4.2.8 on 2023-12-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='musicians/')),
                ('bio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='songs/')),
                ('cover', models.ImageField(upload_to='songs/')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musician')),
            ],
        ),
    ]
